version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./sql-scripts:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: nytdata
    ports:
      - "5434:5432"
  
  redis: # Define the Redis service
    image: redis:latest
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"

  backend:
    build: ./api/python/
    ports:
      - "8050:8050"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/nytdata
      REDIS_URL: redis://:redis@redis:6379
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8050
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:

