# fly.toml app configuration file generated for news-headline-trends on 2023-05-18T23:36:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "news-headline-trends"
primary_region = "lhr"

[http_service]
  internal_port = 8050
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
