
version: 2

sources:
  - name: raw_data
    tables:
      - name: nytdata
        description: Headlines published by NYT (and associated article metadata)
        columns:
          - name: headline
            description: Headline of article.
            tests:
              - not_null

          - name: pub_date 
            description: Publication timestamp
            tests:
              - not_null

          - name: document_type 
            description: Type of document. One of 'article', 'multimedia', 'audio', 'audiocontainer'.
            tests: 
              - accepted_values:
                  values: ['article', 'multimedia', 'audio', 'audiocontainer']

          - name: news_desk 
            description: Desk in the newsroom that worked on the story

          - name: type_of_material
            description: Type of article (News, Correction, Op-Ed, ...)

          - name: word_count 
            description: Number of words in article.

          - name: web_url 
            description: URL of article. 

          - name: source 
            description: Article source. 
            tests:
              - accepted_values:
                  values: ['The New York Times']

          - name: section_name
            description: Section that the article appeared in.

          - name: filename
            description: Parquet source file.
          
      - name: allow_words
        description: Words available to select in dropdown.
        columns:
          - name: allow_word
            description: Word to be included in dropdown.
            tests:
              - unique
              - not_null

models:
  - name: monthly_content_counts
    description: Number of articles in each section per month.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - year_month
            - section_name
    columns:
      - name: year_month
        description: Month of year

      - name: section_name
        description: Section that the article appeared in.

      - name: num_articles
        description: Number of articles

  - name: word_headlines
    description: Selected words and headlines they appear in 
    columns:
      - name: word 
        tests:
          - not_null

      - name: year_month
        tests:
          - not_null

      - name: headline
        tests:
          - not_null

